### ISSUE TITLE
Add `format` command

### ISSUE THREAD

**Issue by passsy** [phntmxyz/sidekick#165]
```bash
$ <cli> format
```
Should format all packages of the repo.

We could also allow customization of the line length per package via `pubspec.yaml`. (As proposed in https://github.com/dart-lang/dart_style/issues/918)

```yaml
# pubspecy.yaml

format:
  line_length: 120
```

Glob exclusions, like in the in `DepsCommand(excludeGlob: ["path/to/**.*dart"])` should be added, too.

**Comment by jxstxn1** [comment]
If this is not set:
```yaml
# pubspecy.yaml

format:
  line_length: 120
```
default should be 80 right?
